kind: pipeline
name: test_docker_pipeline

environment:
  DEFAULT_NAME: FOO BAR

steps:
- name: prep
  image: maven:3-jdk-10
  commands:
  - mvn --version

- name: hello_world_echo
  image: ubuntu:latest
  commands:
  - echo "Hello World!"
  - echo "Repo:$DRONE_REPO_NAME"
  - echo "Stage:$DRONE_STAGE_NAME"
  - echo "Step:$DRONE_STEP_NAME"
  - echo "Secret text 1:$SECRET1"
  - echo "Secret text 2:$SECRET2"
  environment:
    SECRET1:
      from_secret: secret1
    SECRET2:
      from_secret: secret2

- name: hello_world_java
  image: openjdk:latest
  commands:
  - javac ./com/priologic/hello/Hello.java
  - java com.priologic.hello.Hello $DEFAULT_NAME
  - java com.priologic.hello.Hello $SECRET1
  - java com.priologic.hello.Hello $SECRET2
  environment:
    SECRET1:
      from_secret: secret1
    SECRET2:
      from_secret: secret2
